name: Build Mimic

on:
  push:
    tags:
      - "v1.0.0"   # 例如 v1.0.0
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Build server
        run: |
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o build/mimic-server-${{ matrix.goos }}-${{ matrix.goarch }} ./server

      - name: Build client
        run: |
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o build/mimic-client-${{ matrix.goos }}-${{ matrix.goarch }} ./client

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mimic-${{ matrix.goos }}-${{ matrix.goarch }}
          path: build/

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./release

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: release/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
